# Uses MiniMessage format and any PlaceholderAPI placeholders.
# You can also add <prefix> and <suffix> at either end of the playername.
joinMessage: "<yellow>%player_name% <yellow>joined the game"
leaveMessage: "<yellow>%player_name% <yellow>left the game"

# You can set these permissions to whatever you want.
# Just make sure they match the permissions in your permissions plugin.
permissions:
  silentjoin: "essentials.silentjoin"
  silentquit: "essentials.silentquit"
  vanish: "essentials.vanish" # This should be the permission to go into vanish-mode (handled by your vanish plugin e.g. EssentialsX).

# Set this to whatever command handles vanish on your server.
commands:
  vanish-on: "essentials:vanish on"
  vanish-off: "essentials:vanish off"